### ISSUE TITLE
question: board choice

### ISSUE THREAD

**Issue by juliusmh** [thnikk/touchPad#1]
Hello there,
currently waiting for my order of the cap touch pad. I can see that you used the `adafruit_itsybitsy_m0` or `adafruit_trinket_m0`. These boards are pretty expensive, do you use a cheap but compatible clone?
What do you think about the `arduino pro mini` which has keyboard capabilites and comes at a cost of 2$/u ? (chinese clone obv). Your prices on ETSY are very competitive considering the microcontroller alone is 10$.

Keep it up :+1:

**Comment by thnikk** [comment]
I use genuine Adafruit Trinket M0s (the itsybitsy M0 was only used in the 4k version.) They are expensive, but there are a lot of features that make them a better value in this application, like:

- They're small so the footprint of the keypad can be reduced.
- They feature an integrated RGB LED, which allows for LED effects on the touch models without having to add an LED.
- They support capactive touch without any additional circuitry, which also works very well.

The pro mini doesn't have a USB port, so it's not really an option. Maybe you mean the Pro Micro, which is based on the Leonardo and natively supports USB? That's actually what I used before I switched to the Trinket M0. However, capacitive touch would require extra circuitry, and, more importantly, the USB ports on those boards are **absolute garbage** (bold necessary.) The price of the Trinket M0 was definitely a bitter pill to swallow at the time, but I think it was a good decision. My products are only as good as the weakest link, so I feel better having switched for the more secure USB port alone. 

I only actually started making the touch models after I switched to the trinket m0 for my other models and noticed (though it was kinda buried in the documentation) that it had cap touch support. They're also 32-bit boards with much more flash, ram, and a faster processor. I'm working on a [full rewrite of the firmware](https://github.com/thnikk/unified) that combines the code for the mechanical and touch models and I do feel like the increased flash and ram has given me a lot more freedom (though definitely way overkill.) 

Thank you for the kind words of encouragement, I really do appreciate it.

**Comment by juliusmh** [comment]
Wow thats an elaborate response. Yes I mean the `micro`, I'm sorry. I used to build my own cap touch controller with some dedicated circuits and had issues with the input power. When run from a USB hub with many other devices the voltage was so unstable that the capacitve touch had too much noise in it to be usable. Lets see if your product performs any better with the luxus chip :wink: 

I'll take a look at your repository for the rewrite. Maybe I can add some flashy RGB effects. What do you think about a desktop app to control sensitivity, RGB colors, key map etc?

**Comment by thnikk** [comment]
What were you using for the actual touch surfaces? I had issues with sensitivity until I covered the metal plates with vinyl. I think I got the idea from Atmel's documentation of the feature (which they call QTouch.) 

Any additional LED effects are welcome. I'm still missing some from the older firmware, but core functionality has priority at the moment since I'd just like to finish it right now and haven't had a lot of time.

What I currently use for user configuration of the keypad is a CLI through serial communication. It's not perfect, but it's fully functional and cross-platform. Ideally I would keep this functionality and have a full GUI program eventually, but that's been too big of an endeavor for me to start on as of yet. Touch sensitivity isn't configurable at the moment (it's actually been very consistent for everyone with the values set in the firmware,) but that is something I'd like to add in the future just in case.

**Comment by juliusmh** [comment]
@thnikk sorry for the late reply. I was using regular metal angles that were supposed to hold a wooden frame. It was not perfect but it had holes so I could screw my connecting wire to it. Maybe this is where the inconsistency already began. 

I thought about transitioning LED colors from green to red when my health is very low in osu!. Also you could match the led with the lighting of the room. You could also use the touchpad as a notification LED which blinks when I get e.g. a new message. Yes this is over-engineered and probably not worth the effort but If we had the possibility to write raw RGB to the device using serial I could start hacking around.

I close this issue as all my questions are answered, thank you.
